import os
from dotenv import load_dotenv

load_dotenv()

DISCORD_API_TOKEN = os.getenv("DISCORD_API_TOKEN")
LOGURU_FILTER_TYPE = os.getenv("LOGURU_FILTER_TYPE")

# PostgreSQL
POSTGRES_DRIVER=os.getenv("POSTGRES_DRIVER")
POSTGRES_USER=os.getenv("POSTGRES_USER")
POSTGRES_PASSWORD=os.getenv("POSTGRES_PASSWORD")
POSTGRES_DB=os.getenv("POSTGRES_DB")
POSTGRES_HOST=os.getenv("POSTGRES_HOST")
POSTGRES_PORT=os.getenv("POSTGRES_PORT")
