"""update Guilds Table

Revision ID: cc83a1930018
Revises: ef431c6e648b
Create Date: 2023-07-11 05:12:37.295406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc83a1930018'
down_revision = 'ef431c6e648b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
