"""change nullable of guilds

Revision ID: ef431c6e648b
Revises: b13ccfc81dd8
Create Date: 2023-07-11 00:37:34.254707

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef431c6e648b'
down_revision = 'b13ccfc81dd8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'guild_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    op.alter_column('guilds', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('guilds', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('guilds', 'config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.alter_column('guilds', 'language',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('guilds', 'guild_id',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    # ### end Alembic commands ###
